# Generated by Django 2.1.5 on 2019-01-21 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_id', models.CharField(max_length=10)),
                ('genres', models.CharField(max_length=30)),
                ('director', models.CharField(max_length=30)),
                ('cover_url', models.URLField()),
                ('plot', models.CharField(max_length=500)),
                ('full_time', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Movies_Shot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shot_id', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=30)),
                ('video_url', models.URLField()),
                ('start_time', models.DurationField()),
                ('end_time', models.DurationField()),
                ('caption', models.CharField(max_length=250)),
                ('movies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Movies')),
            ],
        ),
    ]
