# Generated by Django 2.1.5 on 2019-01-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='themes',
            field=models.CharField(default='default', max_length=30),
            preserve_default=False,
        ),
    ]
