# Generated by Django 2.1.5 on 2019-01-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_movies_themes'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies_shot',
            name='theme',
            field=models.CharField(default='war', max_length=30),
            preserve_default=False,
        ),
    ]
