# Generated by Django 2.1.5 on 2019-02-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_movies_themes'),
    ]

    operations = [
        migrations.CreateModel(
            name='k_Shot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shot_id', models.CharField(max_length=10)),
                ('genres', models.CharField(max_length=100)),
                ('themes', models.CharField(max_length=100)),
                ('plots', models.CharField(max_length=100)),
                ('duration', models.DurationField()),
                ('url', models.URLField()),
            ],
        ),
    ]
