# Generated by Django 2.1.7 on 2019-03-08 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_movies_shot_theme'),
        ('backend', '0003_k_shot'),
    ]

    operations = [
    ]
